### ISSUE TITLE
BOJ 1405 미친로봇

### ISSUE THREAD

**Issue by KodaHye** [footdev/Algorithm_Study#20]

**Comment by KodaHye** [comment]
맨 마지막 기저조건에서 계산을 하는 것보다 계산값을 변수로 전달하는게 시간상 효율이 좋다!
정확한 이유는 모르겠지만, point 클래스를 사용하는 것보다 직접 함수에 점의 위치를 int, int로 매개변수로 전달해주는것이 메모리 효율이 6배 더 좋았다!

**Comment by Holdm2t1ght** [comment]
...! 짱

**Comment by gudtjr2949** [comment]
당신 천재야?

**Comment by KodaHye** [comment]
@gudtjr2949 먼저 그렇게 풀었길래 따라서 그렇게 푼건데, 혹시 자기소개하는건가요?
